### ISSUE TITLE
mapper 작성

### ISSUE THREAD

**Issue by ak2j38** [f-lab-edu/in-bob-we-trust#38]

**Comment by JooHyukKim** [comment]
## Description

- dependency 로 추가된 `mybatis`를 활용합니다.

## Tasks
- [ ] 테스트를 위한 h2 데이터베이스 설정
- [ ] `*Repository 인터페이스`들의 mapper.xml 작성
- [ ] `*Mapper`테스트 코드 작성

**Comment by JooHyukKim** [comment]
## Notes
- 이번 이슈의 subissue들이 전부 반영되었습니다.
