### ISSUE TITLE
테스트 Actions 고도화

### ISSUE THREAD

**Issue by JooHyukKim** [f-lab-edu/in-bob-we-trust#41]
## Description
- `Functional` 과 `Integration` 테스트로 분개합니다.
- Github Action를 통해 위 테스트 전략을 CI 프로세스에 자동화합니다.

## Tasks
- [x] `Functional-Integration` 테스트 분리전략 리서치
- [x] 프로젝트 적용 계획
- [x] 다른 `git repo` 에서 깃허브 액션 적용 테스트
- [x] 반영
- [x] `local` 테스트
- [x] 기존 actions `테스트 Job`의 build 태스크 삭제
