### ISSUE TITLE
mybatis 및 테스트용 DB 설정

### ISSUE THREAD

**Issue by JooHyukKim** [f-lab-edu/in-bob-we-trust#45]
## Tasks
- [x] `testRuntime` 을 위한 H2 database 설정 `file` & `MySQL 모드`
- [x] 커넥션 테스트
- [x] initial data 설정
- [x] `mybatis` 매퍼 관련 설정 적용
- [x] 테스트용 Sample 매퍼 작성

### mybatis 매퍼설정

- 본격적인 Mapper 작성 이전에 실행 여부 확인을 위한 간단한 테스트작성

### H2 database 설정
- H2 database 는 `mem, file, embedded, server 모드` 존재
- 가장 간단한 `in-memory db` 적용
